### ISSUE TITLE
Keycloak version 15.0.0 support

### ISSUE THREAD

**Issue by jord1e** [bitnami/bitnami-docker-keycloak#16]
Keycloak [version 15.0.0 was released](https://github.com/keycloak/keycloak/releases/tag/15.0.0) friday the 30th, with better support for User Profiles and better compliance with the Financial-grade API (FAPI).

I tried forking the repository and implementing 15.0.0 support myself but stumbled upon the `.bitnami_components.json` file and gave up.

When will 15.0.0 support be implemented?

Changelog for reference (`14.0.0...15.0.0`):
https://github.com/keycloak/keycloak/compare/14.0.0...15.0.0

**Comment by marcosbc** [comment]
Hi @jord1e, due to summer holidays the release will get a bit delayed, so we are expecting it to happen during the next 2-3 weeks.

**Comment by jord1e** [comment]
Thank you, marco

**Comment by petersonfs** [comment]
@marcosbc the version upgrade is only made by the bitnami team? Or we can help in some way?

**Comment by marcosbc** [comment]
@petersonfs The new version requires us to make some changes to our internal metadata, to support the new 15.0.0 major/branch. Once added, our pipeline will execute a test suite to ensure that everything works perfectly, and if it does, release it.

Unfortunately there's not much that can be done externally to help with these efforts right now. However, we don't expect there to be any issues with the test suite, so probably once we add support for the new branch in our pipeline, it should be released. However due to summer holidays, I'm unable to give an ETA for when that will happen (since we have a limited capacity right now, and also a backlog with other pending releases).

**Comment by petersonfs** [comment]
I get it @marcosbc, thanks!

**Comment by petersonfs** [comment]
Just a reminder, Keycloak had a minor fix and the latest version is 15.0.1.

**Comment by marcosbc** [comment]
Hi, we have still not started working on this unfortunately. However, it seems like Keycloak 15.x is next on the list of new releases to perform, so it is likely that we start working on it during this week.

**Comment by jord1e** [comment]
[15.0.2 was released](https://github.com/keycloak/keycloak/releases/tag/15.0.2) 😅.

**Comment by marcosbc** [comment]
Hi all, just wanted to let you know that the `bitnami/keycloak:15.0.2-debian-10-r0` container image was just [released this morning as well](https://github.com/bitnami/bitnami-docker-keycloak/commit/f02f28d21f742b66ac24e71a32034a258a8a6a55).
