### ISSUE TITLE
Not able to access WildFly web graphical interface.

### ISSUE THREAD

**Issue by ziad-saade** [bitnami/bitnami-docker-keycloak#30]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by carrodher** [comment]
In order to provide the proper support:
1. In the title you mention WildFly but the issue was created in the keycloak repository. Can you 1) edit the title if it belongs to keycloak or 2) open it in the [WildFly repository](https://github.com/bitnami/bitnami-docker-wildfly/issues)?
2. We need more info in order to reproduce the issue, can you please fill in the template that appears when creating new issues?

**Comment by ziad-saade** [comment]
> In order to provide the proper support:
> 
> 1. In the title you mention WildFly but the issue was created in the keycloak repository. Can you 1) edit the title if it belongs to keycloak or 2) open it in the [WildFly repository](https://github.com/bitnami/bitnami-docker-wildfly/issues)?
> 2. We need more info in order to reproduce the issue, can you please fill in the template that appears when creating new issues?

Keycloak is a war file deployed under WildFly, wha
