### ISSUE TITLE
Keycloak 16.1.0 is available

### ISSUE THREAD

**Issue by yarons** [bitnami/bitnami-docker-keycloak#40]
Are there any upgrade plans?

Thanks.

**Comment by carrodher** [comment]
Thanks for letting us know, usually minor or patch versions are released automatically once detected by our tracking system.
In the case of new major versions like this one, some manual effort is needed on our side in order to adapt the test & release pipeline for the changes in the upstream application.

Our system already detected the new version but the team needs to work on it, it should be available in the next few days or weeks.

**Comment by dgomezleon** [comment]
Hello @yarons 

Keycloak 16.1.0 has been released. 

We proceed to close this issue.
