### ISSUE TITLE
Vulnerabilities found on image

### ISSUE THREAD

**Issue by sergiojoker11** [bitnami/bitnami-docker-keycloak#43]
**Description**

There are some important vulnerabilities in the container.

**Steps to reproduce the issue:**

1. Scan docker container
2. See results

**Describe the results you received:**

Vulnerabilities found in the container

**Describe the results you expected:**

At least high and the most important medium vulnerabilities to be resolved

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

I wonder if switching base image from debian to alpine is a good move.

[SECURITY-REPORT (1).pdf](https://github.com/bitnami/bitnami-docker-keycloak/files/7869766/SECURITY-REPORT.1.pdf)

**Comment by carrodher** [comment]
Hi, unfortunately, those security vulnerabilities are not fixed by the OS itself, so although we built the images on a daily basis, this kind of CVE will be reported while there is not a new version patching the issue in the OS.
You can find more info in [this blog post](https://docs.bitnami.com/kubernetes/open-cve-policy/).

[This CVE scan report](https://quay.io/repository/bitnami/keycloak?tab=tags) contains a security report with all open CVEs. To get the list of actionable security issues, find the "latest" tag, click the vulnerability report link under the corresponding "Security scan" field and then select the "Only show fixable" filter on the next page.

The Bitnami Open Source/Community Catalog is based on Debian but Bitnami/VMware provides a custom containers and Helm Charts catalog based on the desired base image (generic distro or custom golden image) through [VMware Tanzu Application Catalog](https://tanzu.vmware.com/application-catalog).
