### ISSUE TITLE
Vulnerabilities Go

### ISSUE THREAD

**Issue by Raufozdemir** [bitnami/bitnami-docker-keycloak#96]
### Name and Version

bitnami/keycloak:18.0.2

### What steps will reproduce the bug?

hi we use twistlock for our security. We are using the keycloak 18.0.2 image that you have published. We are getting old version error about "go" from twistlock. Are you going to make any improvements regarding this situation?

### What do you see instead?

[CVE-2022-23806](https://nvd.nist.gov/vuln/detail/CVE-2022-23806)

[CVE-2021-38297](https://nvd.nist.gov/vuln/detail/CVE-2021-38297

![Critical](https://user-images.githubusercontent.com/40164810/179786449-971510c5-7ad2-4e9f-8fd8-30c6cd0fdc59.PNG)
)

**Comment by carrodher** [comment]
Hi, unfortunately, those security vulnerabilities are not fixed by the OS or the application itself, so although we built the images on a regular basis to provide the latest version of system packages, this kind of CVE will be reported while there is no new version patching the issue in the OS or the application.

The Bitnami Application Catalog (OpenSource) is based on Debian 11 but Bitnami, as part of VMware, provides a custom container and Helm Charts catalog based on the desired base image (generic distro such as Debian 10 & 11, CentOS 7, PhotonOS 3 & 4, Ubuntu 18.04 & 20.04, or custom golden image) through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

**Comment by fmulero** [comment]
We are moving to [a new repository](https://github.com/bitnami/containers) in order to be aligned with the approach followed in [bitnami/charts](https://github.com/bitnami/charts). More information [here](https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html). If you are still interested on this issue, please open a new issue in [bitnami/containers](https://github.com/bitnami/containers) repository
